const TableauBoutique = [
  {nom: " Nifty Shoe",categorie:"Femme",prix:"35.55"},
{nom: "Trend Shoe",categorie:"Femme",prix:"35.55"},
{nom: "Cue Shoe",categorie:"Femme",prix:"340.348"},
{nom: "Dungeon Shoe",categorie:"Femme",prix:"960"},
{nom: "Force Shoe",categorie:"Femme",prix:"85.66"},
{nom: "Shoely",categorie:"Femme",prix:"958.84"},
{nom: "Shoenest",categorie:"Femme",prix:"423.431"},
{nom: "Shoeish",categorie:"Femme",prix:"655"},
{nom: "Shoebes",categorie:"Femme",prix:"54"},
{nom: "Frost Shoe",categorie:"Homme",prix:"8765"},
{nom: "Wedge Shoe",categorie:"Homme",prix:"808"},
{nom: "Gene Shoe",categorie:"Homme",prix:"0864.65"},
{nom: "Club Shoe",categorie:"Homme",prix:"876.98"},
{nom: "saluAnti Shoettt",categorie:"Enfant",prix:"34"},
{nom: "salGlide Shoeu",categorie:"Enfant",prix:"9777"},
{nom: "Ultra Shoe",categorie:"Enfant",prix:"786"},
{nom: "saWedge Shoett",categorie:"Enfant",prix:"43.99"},
{nom: "Complex Shoe",categorie:"Enfant",prix:"212"},
]
